### ISSUE TITLE
Is there a way to initialize observable properties to nil?

### ISSUE THREAD

**Issue by rmvz3** [blendle/Hanson#13]
Let's say I'd like to observe a property of type UIImage. Is there a way of make it nil by default?

Something like:

    let observableImage : UIImage? = Observable(nil)

**Comment by smeis** [comment]
Hi @rmvz3,

Yes that's possible, you can declare the property like this:

`let observableImage = Observable<UIImage?>(nil)`

**Comment by rmvz3** [comment]
Great. Thanks!
