### ISSUE TITLE
Update for Swift 4 please

### ISSUE THREAD

**Issue by MKGitHub** [blendle/Hanson#16]
Update for Swift 4 please

**Comment by boyvanamstel** [comment]
Hi there, thanks for your comment. We'll add a Swift 4 branch soon!

**Comment by boyvanamstel** [comment]
@MKGitHub I've Started a swift 4 branch: https://github.com/blendle/hanson/tree/swift4

**Comment by MKGitHub** [comment]
Please finalize swift4 branch and merge into master, it is been a while now.

**Comment by joostvandijk** [comment]
@MKGitHub It's been merged!
