### ISSUE TITLE
Observing Array

### ISSUE THREAD

**Issue by Prince2k3** [blendle/Hanson#19]
How would you go about observing an array using Hanson?

**Comment by boyvanamstel** [comment]
Hi there, here's an example:

```Swift
import UIKit
import Hanson

class ViewController: UIViewController {

    private let array = Observable<[String]>([])
    
    override func viewDidLoad() {
        super.viewDidLoad()

        bind(array, to: self) { (_, array) in
            print("Array changed to \(array)")
        }

        array.value = ["Hello", "World"]
    }

}
```

The output:

```
Array changed to []
Array changed to ["Hello", "World"]
```

Let me know if this is what you were looking for.

**Comment by Prince2k3** [comment]
This is kind of...I was looking for an instance where I can use sequence methods like `contains`, `append`.  Seems there are no value when I do those operations. You have to set a new array in order to get a trigger.

**Comment by joostvandijk** [comment]
Hi there,

You could call `.append(_:)` directly on the `value` property:
```
array.value.append(“Test”)
```

This should result in an event.

**Comment by Prince2k3** [comment]
Hmm... ok then I'm doing something off. I wanted to verify with you guys how observing array works. I ran the code approve in a Test project and that all worked!  I'll figure it out. :) 

Thanks!
