### ISSUE TITLE
observe one property of complex object?

### ISSUE THREAD

**Issue by wdcurry** [blendle/Hanson#20]
I am not quite sure how to approach this and think my understanding of Hanson is not yet up-to-speed.  I have a complex object from another repo.  It is very deep and async-oriented. I want to track at least one property from it, and prefer not to tap into their repo to make changes.  Without those changes, is something like this possible?

I want to track the duration property of the youtube API return values from player within youtubeKit, if that helps. And i understand if this is too complex to ask! thx...

**Comment by joostvandijk** [comment]
Hey! Thanks for using Hanson.
If the property is Key-Value Observable, then your best bet would be to create a dynamic observable that wraps the property that you want to observe. You can find an example of this in the README, where UITextField’s text property is observed. Does that help?

**Comment by wdcurry** [comment]
I’m not sure. Thus far I’ve never used KVO,  so I can’t answer the question regarding if the property is KV observable. I set up a test following that code, but changes to the property did not result in any activation of the event I set up.

**Comment by joostvandijk** [comment]
I’ce looked at the YoutubeKit I could find on GitHub, and it seems that it’s a Swift project. Since KVO is only available on Objective-C properties, this approach is not going to work. Therefore, I’m afraid this isn’t possible without modifying the library.

**Comment by wdcurry** [comment]
Thank you for the rapid answers!  I’ll look into creating my own pseudo-observable the, via the async feed from YT. Should be easy enough but too bad as I liked the feel of your repo!

**Comment by joostvandijk** [comment]
No worries! I hope it can be of use in the future.
